# https://github.com/actions/starter-workflows/blob/main/ci/dotnet.yml
# https://github.com/actions/setup-dotnet
name: build-test
on:
  workflow_call:
jobs:
  build-test-deploy:
    # Our apps runs on alpine, but using alpine_latest here doesn't work as we just get:
    # Waiting for a runner to pick up this job...
    # in github. We'll use Ubuntu for now
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all history. Necessary for gitversion (to find correct version tag..?)
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/Finanstilsynet/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore
        run: dotnet restore
      - name: Build
        run: |
          dotnet build \
          --configuration Release \
          --no-restore \
          /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
          /p:AssemblyFileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
          /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      - name: Test
        run: |
          dotnet test \
          --configuration Release \
          --no-build
