name: build-on-push
on:
  push:
    branches:
      # Pushing a tag will also trigger a push event. We run another workflow on
      # version tags, so we should not run this workflow. This pattern means we'll
      # only run on pushes to branches and not tags.
      # See https://github.community/t/dont-run-on-tag-creation/137469/7
      - '**'
  pull_request:
jobs:
  build-test:
    uses: ./.github/workflows/build-test.yaml
