name: deploy-latest-tag
on:
  push:
    tags:
      - v*
jobs:
  build-test:
    uses: ./.github/workflows/build-test.yaml
  deploy:
    # Our apps runs on alpine, but using alpine_latest here doesn't work as we just get:
    # Waiting for a runner to pick up this job...
    # in github. We'll use Ubuntu for now
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nupkg
      - name: Publish
        run: |
          dotnet nuget push **/Finanstilsynet.Altinn.Public.*.nupkg \
          --skip-duplicate \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source https://nuget.pkg.github.com/Finanstilsynet/index.json
